name: Build and Publish Docker Image

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push service Acc image
        run: |
          docker build -t pydev07/service-a:latest ./services/acc
          docker push pydev07/service-acc:latest

      - name: Build and push service GL image
        run: |
          docker build -t pydev07/service-b:latest ./services/gl
          docker push pydev07/service-gl:latest
